language: haxe
haxe:
  - "3.2.0"
  #- development # Commented out until we have time to investigate the failures.
env:
  - MYSQL_HOST="127.0.0.1" MYSQL_PORT="3306" MYSQL_USER="root" MYSQL_PASSWORD="" MYSQL_DATABASE="test" # For ufront-orm tests
hxml:
  - tool.hxml
  - doc.hxml
before_install:
  - sudo apt-get install neko
  - mysql -e "create database IF NOT EXISTS test;" -uroot # For ufront-orm tests.
before_script:
  - yes | haxelib install ufront # For installing all the dependencies that aren't in the submodules.
  - yes | haxelib install dox # For compiling API docs.
  - yes | haxelib install detox # For ufront-mvc unit tests.
  - yes | haxelib install mockatoo # For compiling API docs, ufront-mvc unit tests.
  - haxelib dev ufront # Get the `ufront` command working.
  - ./setupDev # Set up the submodules as the `haxelib dev` paths.
script:
  - ./runtests
