language: haxe
haxe:
  - "3.2.0"
  - development
env:
  - MYSQL_HOST="127.0.0.1" MYSQL_PORT="3306" MYSQL_USER="root" MYSQL_PASSWORD="" MYSQL_DATABASE="test"
hxml:
  - tool.hxml
  - doc.hxml
before_install:
  - sudo apt-get install neko
  - mysql -e "create database IF NOT EXISTS test;" -uroot
before_script:
  - ./setupDev
script:
  - ./runtests
