language: haxe
haxe:
  - "3.2.0"
  - development
neko: "2.0.0"
matrix:
  allow_failures:
    - haxe: development # Allow development to fail until I have time to investigate.
env:
  - MYSQL_HOST="127.0.0.1" MYSQL_PORT="3306" MYSQL_USER="root" MYSQL_PASSWORD="" MYSQL_DATABASE="test" # For ufront-orm tests
before_install:
  - sudo add-apt-repository ppa:ondrej/php5 -y
  - sudo apt-get update -q
  - sudo apt-get install php5-cli
  - mysql -e "create database IF NOT EXISTS test;" -uroot # For ufront-orm tests.
install:
  - yes | haxelib install ufront # For installing all the dependencies that aren't in the submodules.
  - yes | haxelib install ufront-client # For installing all the dependencies that aren't in the submodules.
  - yes | haxelib install dox # For compiling API docs.
  - yes | haxelib install utest # For compiling API docs.
  - yes | haxelib install detox 1.0.0-rc.10 # For ufront-mvc unit tests.
  - yes | haxelib install mockatoo # For compiling API docs, ufront-mvc unit tests.
  - ./setupDev # Set up the submodules as the `haxelib dev` paths.
  - haxelib list
  - echo $(ls -l ~/neko)
  - echo $(php --version)
  - echo $(apt-cache showpkg php5-cli)
hxml:
  - tool.hxml
  - doc.hxml
before_script:
script:
  - ./runtests
